import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Zap, Menu, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
export const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsx(motion.nav, { initial: { y: -100 }, animate: { y: 0 }, transition: { duration: 0.6 }, className: "fixed top-0 left-0 right-0 z-50 glass border-b border-white border-opacity-10", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs(Link, { to: "/", className: "flex items-center space-x-2 group", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-primary-500 to-accent-500 rounded-lg group-hover:shadow-glow transition-all duration-300", children: _jsx(Zap, { className: "w-5 h-5 text-white" }) }), _jsx("span", { className: "text-xl font-bold gradient-text", children: "TechNavigator" })] }), _jsxs("div", { className: "hidden md:flex items-center space-x-8", children: [_jsx(Link, { to: "/", className: "text-gray-300 hover:text-primary-400 transition-colors duration-300 font-medium", children: "Home" }), _jsx("a", { href: "#careers", className: "text-gray-300 hover:text-primary-400 transition-colors duration-300 font-medium", children: "Careers" }), _jsx("a", { href: "#features", className: "text-gray-300 hover:text-primary-400 transition-colors duration-300 font-medium", children: "Features" })] }), _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "md:hidden text-gray-300 hover:text-primary-400 transition-colors", children: isOpen ? _jsx(X, { className: "w-6 h-6" }) : _jsx(Menu, { className: "w-6 h-6" }) })] }), isOpen && (_jsxs(motion.div, { initial: { opacity: 0, y: -10 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -10 }, className: "md:hidden pb-4 border-t border-white border-opacity-10", children: [_jsx(Link, { to: "/", className: "block px-4 py-2 text-gray-300 hover:text-primary-400 hover:bg-primary-500 hover:bg-opacity-10 rounded transition-colors", children: "Home" }), _jsx("a", { href: "#careers", className: "block px-4 py-2 text-gray-300 hover:text-primary-400 hover:bg-primary-500 hover:bg-opacity-10 rounded transition-colors", children: "Careers" }), _jsx("a", { href: "#features", className: "block px-4 py-2 text-gray-300 hover:text-primary-400 hover:bg-primary-500 hover:bg-opacity-10 rounded transition-colors", children: "Features" })] }))] }) }));
};
